name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      #- name: Make Gradle wrapper executable
      #  run: chmod +x ./gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set gradlew exec perm
        run: chmod +x ./gradlew

      - name: Set up Gradle (system)
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.5'
          
      - name: Run make
        run: make
  
      - name: Run check
        run: make check
  
      - name: Run distcheck
        run: make distcheck

      - name: Upload Desktop JAR(s)
        uses: actions/upload-artifact@v4
        with:
          name: desktop-artifacts
          path: desktop/build/libs/*.jar
